# Generated by Django 4.1.12 on 2023-11-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=100)),
                ('dishDesc', models.CharField(max_length=200)),
                ('dishPrice', models.IntegerField()),
                ('dishImage', models.FileField(blank=True, null=True, upload_to='dishes/')),
            ],
        ),
    ]
